### ISSUE TITLE
[hardware_interface-7] process has died

### ISSUE THREAD

**Issue by yo4hi6o** [nisshan-x/mycobot_moveit#19]
I am a ROS beginner.

I am trying to connect mycobot to ROS, but when I try [roslaunch mycobot_moveit mycobot_moveit_control.launch],
 the notation error occurs and the actual robot does not work.

![Screenshot from 2021-08-04 11-33-27](https://user-images.githubusercontent.com/74748434/128112648-d1cdcb0d-8364-4e7e-afaa-09aff4ad2f2e.png)

My environment is as follows.

ubuntu20.04
noetic
mycobot
AtomMain2.4

Do you know how to resolve this error?

thank you

**Comment by nisshan-x** [comment]
Hi.

Sorry, it's the first time to see that error. In your screenshot, an error happened before process died. I guess that is the hint  to solve.

**Comment by yo4hi6o** [comment]
It worked in a melodic environment.
 Thank you very much.

**Comment by nisshan-x** [comment]
Good!
