### ISSUE TITLE
Gazebo doesn't work.

### ISSUE THREAD

**Issue by nisshan-x** [nisshan-x/mycobot_moveit#9]
I created `mycobot_moveit_gazebo.launch` to launch Gazebo to run virtual myCobot, but it doesn't work. It happens that TF is broken, but I'm not sure how to fix the issue.

I need help!

Thanks.

**Comment by karaage0703** [comment]
@nisshan-x 
I send PR #18 

In my environment(native ubuntu PC), this PR works fine.

https://zenn.dev/karaage0703/books/3be6bad93b0c8e/viewer/eec47d

**Comment by nisshan-x** [comment]
Thank you so much!!!
